"""Generate personal SKILL.md from extracted patterns + role templates."""

from __future__ import annotations

from pathlib import Path
from datetime import datetime, timezone

from plus_me.config import ENHANCED_SKILL_DIR, PATTERNS_DIR, ROLE_TEMPLATES_DIR


def _ensure_dir(p: Path) -> None:
    p.mkdir(parents=True, exist_ok=True)


def load_role_template(role: str) -> str | None:
    """Load a role template by name. Returns None if not found."""
    path = ROLE_TEMPLATES_DIR / f"{role}.md"
    if path.exists():
        return path.read_text(encoding="utf-8")
    return None


def available_roles() -> list[str]:
    """List available role template names."""
    if not ROLE_TEMPLATES_DIR.exists():
        return []
    return [f.stem for f in ROLE_TEMPLATES_DIR.glob("*.md")]


def save_patterns(judgment: str, style: str, priorities: str) -> dict:
    """Save extracted patterns to output/patterns/ directory."""
    _ensure_dir(PATTERNS_DIR)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    files = {
        "judgment.md": (
            f"---\nname: Judgment Patterns\ndescription: How this user makes decisions\n"
            f"type: judgment\nupdated: {now}\n---\n\n{judgment}"
        ),
        "style.md": (
            f"---\nname: Communication Style\ndescription: How this user communicates and formats output\n"
            f"type: style\nupdated: {now}\n---\n\n{style}"
        ),
        "priorities.md": (
            f"---\nname: Work Priorities\ndescription: What this user focuses on and cares about\n"
            f"type: priorities\nupdated: {now}\n---\n\n{priorities}"
        ),
    }

    saved = {}
    for fname, content in files.items():
        path = PATTERNS_DIR / fname
        path.write_text(content, encoding="utf-8")
        saved[fname] = str(path)

    return saved


def read_patterns() -> dict[str, str] | None:
    """Read existing patterns from output/patterns/. Returns None if not found."""
    if not PATTERNS_DIR.exists():
        return None

    result = {}
    for name in ("judgment", "style", "priorities"):
        path = PATTERNS_DIR / f"{name}.md"
        if path.exists():
            result[name] = path.read_text(encoding="utf-8")

    return result if result else None


def generate_skill(
    judgment: str,
    style: str,
    priorities: str,
    role: str | None = None,
    custom_instructions: str | None = None,
) -> str:
    """Generate a personal SKILL.md from patterns and optional role template."""
    role_section = ""
    if role:
        template = load_role_template(role)
        if template:
            role_section = (
                f"\n## Role Enhancement: {role.upper()}\n\n"
                f"Incorporate these industry best practices while maintaining "
                f"the user's personal style:\n\n{template}\n"
            )

    custom_section = ""
    if custom_instructions:
        custom_section = f"\n## Additional Instructions\n\n{custom_instructions}\n"

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    skill_content = f"""---
name: enhanced-self
description: User's personal behavioral patterns (judgment, style, priorities). Use when writing code, drafting messages, making decisions, or reviewing work for this user.
---

# Your User's Personal Patterns

This skill was auto-generated by Plus-Me on {now}.
It captures how this user thinks, communicates, and makes decisions.
When acting on behalf of this user, follow these patterns.

## Decision-Making & Judgment

{judgment}

## Communication & Output Style

{style}

## Work Priorities & Focus Areas

{priorities}
{role_section}{custom_section}
## How to Apply These Patterns

- When drafting emails, messages, or documents: match the user's communication style
- When making recommendations: align with their decision-making patterns
- When prioritizing tasks: follow their priority framework
- When uncertain: default to their typical approach as shown in the patterns above
- Always maintain the user's voice — this skill should make output feel like it came from them, not from a generic AI
"""

    return skill_content


def save_skill(skill_content: str) -> str:
    """Save generated skill to skills/enhanced-self/SKILL.md."""
    _ensure_dir(ENHANCED_SKILL_DIR)
    path = ENHANCED_SKILL_DIR / "SKILL.md"
    path.write_text(skill_content, encoding="utf-8")
    return str(path)
